language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-21.1.1

before_script:
  # Grant execution permissions to Gradle wrapper
  - chmod +x gradlew
